name: job_baraka
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.5
  easy_localization: ^3.0.3
  shared_preferences: ^2.2.2
  pinput: ^3.0.1
  google_maps_flutter: ^2.5.3
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  another_flushbar: ^1.12.30
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.2.5
  image: ^4.1.7
  location: ^5.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.10
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/marketing.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/marketing.png"
  remove_alpha_ios: true

flutter_native_splash:
  image: assets/logo.png
  color: "#FFFFFF"
  android_12:
    image: assets/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/marketing.png
    - assets/
    - assets/images/slide_1.svg
    - assets/images/slide_2.svg
    - assets/translations/
    - assets/icons/ic.svg
    - assets/icons/ic_call_history.svg
    - assets/icons/ic_change_language.svg
    - assets/icons/ic_edit_profile.svg
    - assets/icons/ic_log_out.svg
    - assets/icons/ic_next.svg
    - assets/icons/ic_worker.svg
    - assets/icons/ic_employer.svg
    - assets/icons/ic_user.png
    - assets/icons/ic_temporary_profile.png

  fonts:
    - family: Mulish
      fonts:
        - asset: fonts/Mulish-Bold.ttf
          weight: 700
        - asset: fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: fonts/Mulish-Medium.ttf
          weight: 500
        - asset: fonts/Mulish-Regular.ttf
          weight: 400



